# Generated by Django 3.2.9 on 2023-02-28 23:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('achieved', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('date_deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Дата срока выполнения')),
                ('date_achieved', models.DateField(blank=True, verbose_name='Дата выполнения')),
                ('time_estimate', models.FloatField(blank=True, verbose_name='Предположительное время выполнения, часы')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tasks', to='tasks.task', verbose_name='Родительская задача')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.PositiveIntegerField(verbose_name='Время, секунды')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись времени',
                'verbose_name_plural': 'Записи времени',
            },
        ),
    ]
